language: ruby

rvm:
  - 2.4.4

addons:
  code_climate:
    repo_token:
      secure: "AGSaueR2sidnTHEWwx+3LgeK543yHn0YJECst4gMJHHC0BElwbvceCWixXiLDaS2SIAiL/m7TckBXxRyXAlRIEUXYiNNeRKxEUCtCHmhkqKjpaPegXo/ogKiejm1dfsuIYwXiAvsMu+G+xIVXhd5szxxtV/A+RtKHJ+HJp0AZOY="
