# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: Simulator 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "Simulator"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alessandro Di Maria"]
  s.date = "2016-03-15"
  s.description = "A simulation container based on Celluloid"
  s.email = "adm@m42.ch"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".gitkeep",
    ".rspec",
    ".ruby-version",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "Simulator.gemspec",
    "circle.yml",
    "config/level_example.yml",
    "lib/sim.rb",
    "lib/sim/version.rb",
    "log/.gitkeep",
    "spec/spec_helper.rb",
    "tasks/doc.rake",
    "tasks/jeweler.rake",
    "tasks/rspec.rake"
  ]
  s.homepage = "http://github.com/grrrisu/Simulator"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "A simulation container based on Celluloid"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<celluloid-io>, ["~> 0.16.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<growl>, [">= 0"])
      s.add_development_dependency(%q<byebug>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<celluloid-io>, ["~> 0.16.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<growl>, [">= 0"])
      s.add_dependency(%q<byebug>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<celluloid-io>, ["~> 0.16.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<growl>, [">= 0"])
    s.add_dependency(%q<byebug>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

