# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "Simulator"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alessandro Di Maria"]
  s.date = "2013-03-28"
  s.description = "A simulation container based on Celluloid"
  s.email = "adm@m42.ch"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "Simulator.gemspec",
    "lib/level.yml",
    "lib/main.rb",
    "lib/sim.rb",
    "lib/sim/buildable.rb",
    "lib/sim/field_properties.rb",
    "lib/sim/guard.rb",
    "lib/sim/level.rb",
    "lib/sim/matrix.rb",
    "lib/sim/object.rb",
    "lib/sim/player.rb",
    "lib/sim/popen/message_serializer.rb",
    "lib/sim/popen/parent_connection.rb",
    "lib/sim/popen/remote_exception.rb",
    "lib/sim/popen/sub_process.rb",
    "lib/sim/queue.rb",
    "lib/sim/time_unit.rb",
    "lib/sim/version.rb",
    "lib/sim/worker.rb",
    "log/.gitkeep",
    "spec/integrations/popen_spec.rb",
    "spec/integrations/sim_spec.rb",
    "spec/level.yml",
    "spec/models/popen/sub_process_spec.rb",
    "spec/models/sim_buildable_spec.rb",
    "spec/models/sim_level_spec.rb",
    "spec/models/sim_matrix_spec.rb",
    "spec/models/sim_object_spec.rb",
    "spec/models/sim_queue_spec.rb",
    "spec/models/sim_time_unit_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/dummy_object.rb",
    "spec/support/popen_test_level.rb"
  ]
  s.homepage = "http://github.com/grrrisu/Simulator"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "A simulation container based on Celluloid"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<celluloid>, ["~> 0.12"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<growl>, [">= 0"])
    else
      s.add_dependency(%q<celluloid>, ["~> 0.12"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<growl>, [">= 0"])
    end
  else
    s.add_dependency(%q<celluloid>, ["~> 0.12"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<growl>, [">= 0"])
  end
end

