require 'rubygems'
require 'bundler/setup'
require 'socket'
require 'celluloid'
require 'celluloid/io'
require 'celluloid/autostart'
require 'active_support'
require 'active_support/core_ext'
require 'eventmachine'

require_relative './ext/hash_ext'

require_relative './sim/version'
require_relative './sim/buildable'
require_relative './sim/object'
require_relative './sim/time_unit'
require_relative './sim/field_properties'
require_relative './sim/matrix'
require_relative './sim/globe'
require_relative './sim/level'
require_relative './sim/player'

require_relative './sim/net/remote_exception'
require_relative './sim/net/message_serializer'
require_relative './sim/net/message_dispatcher'
require_relative './sim/net/parent_connection'
require_relative './sim/net/sub_process'
require_relative './sim/net/player_proxy'
require_relative './sim/net/player_server'
require_relative './sim/net/player_connection'

require_relative './sim/queue/event.rb'
require_relative './sim/queue/sim_event.rb'
require_relative './sim/queue/action_event.rb'
require_relative './sim/queue/fire_worker.rb'
require_relative './sim/queue/event_broadcaster.rb'
require_relative './sim/queue/event_queue.rb'
require_relative './sim/queue/sim_loop.rb'
require_relative './sim/queue/master.rb'

RAILS_ENV = 'development' unless defined? RAILS_ENV
